### ISSUE TITLE
Название, адрес, и поля продукта компании надо дублировать на английском языке.

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#102]
Реализовать функцию транслитерации текста и применить её для:
 - Названия компании (Короткое и полное) ;
 - Адресов;
 - Поля продукта компании??? Какого продукта?

**Comment by 500alex** [comment]
Реализована функция translit() в компоненте company.vue. Заменяет данные полей которые приходят с сервера на латинский транслит. Эти латинские название у пользователя есть возможность поменять, если он считает что транслит должен быть другой.
