### ISSUE TITLE
Список валют, которые должна поддерживать система

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#103]
- [X] Доллар США,
- [X] Евро,
- [X] Английский Фунт, Great Britain Pound (GBP)
- [X] Швейцарский Франк, Swiss Franc (CHF)
- [X] Японская Йена, Japanese Yen (JPY)
- [X] Китайский Юань,  Chinese Yuan (CNY)
- [X] Российский рубль,
- [X] Дирхам ОАЭ,
- [X] Саудовский Риал, Saudi Riyal (SAR)
- [X] Оманский Риал, Omani Rial (OMR)
- [X] Гонконгский Доллар,Hong Kong Dollar (HKD)
- [X] Сингапурский Доллар, Singapore Dollar (SGD)
- [X] Канадский доллар, Canadian Dollar (CAD)
- [X] Австралийский доллар,Australian Dollar (AUD)
- [X] Новозеландский доллар, New Zealand Dollar (NZD)
- [X] Тайваньский Доллар, New Taiwan Dollar (TWD) 
- [X] Южнокорейская Вона, Won (KRW)
- [X] Индийская Рупия, Indian Rupee (INR)
- [X] Шри-ланкийская Рупия,Sri Lanka Rupee LKR
- [X] Индонезийская Рупия, Rupiah (IDR)
- [X] Пакистанская Рупия, Pakistan Rupee (PKR)
- [X] Тайский Бат, Baht (THB)
- [X] Вьетнамский Донг, Vietnamese Dong (VND)

**Comment by 500alex** [comment]
Список необходимых валют добавлен в main.js
