### ISSUE TITLE
Текстовые правки и мелкие доработки от 05.03.2019

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#108]
- [x] Перенести поле social networks в раздел Ptivate в профайле.
- [x] Поле Nationality переименовать в Place of Birth и Поле Citizenship переименовать в Nationality
- [x] На хоумпэйджах номера телефонов высвечиваются без плюсиков впереди.
- [ ] Переперевести тексты на английский язык.
- [x] Поле promocode перенести в раздел Confidential
- [x] Поле Occupation переименовать в СЕО role name и перенести в раздел General.
- [ ] Под полем СЕО role name добавить поле Credentials document
- [x] Поле Tick if this company VAT registered поменять на Tick if this company TAX registered чтобы автоматически определять схему налогообложения.

**Comment by 500alex** [comment]
"На хоумпэйджах номера телефонов высвечиваются без плюсиков впереди"
Некоторые телефоны прилетаю с + , а некоторые нет.  В разметке + поставил но тогда нужно очистить данные телефонов от плюсов.

**Comment by 500alex** [comment]
"Под полем СЕО role name добавить поле Credentials document"
ОП данной задаче нужно уточнение. Какой тип поля подразумевается. Input, autocomplite иди просто текстовое.

**Comment by 500alex** [comment]
"Переперевести тексты на английский язык."
ПО задаче нужны переводы  от проджектов...
