### ISSUE TITLE
Переход к статусу COMPLETED

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#121]
![Screenshot_20190328_164019](https://user-images.githubusercontent.com/43605110/55162123-2cbcb200-5178-11e9-89c1-0e407ed436df.png)
После выполнения всех обязательств кнопка complete должна сравнивать сумму отправленных и полученных средств:
1.Если разница в суммах меньше 3 % уведомить об этом юзера через нотификацию в системе о подтверждении перехода на следующий статус.
2.Если разница в суммах больше 3 % уведомить об этом юзера через нотификацию в системе о пересоздании заказа.

**Comment by gewisser** [comment]
fixed now
