### ISSUE TITLE
Исправление пробелов и отступов в нотификациях

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#127]
Просмотреть и протестировать все нотификации. Почти в каждой нотификации есть проблемы с пробелами и отступами.

### **Нет пробела**
![image](https://user-images.githubusercontent.com/5417292/55385432-d2d03980-5535-11e9-9ef7-96ca935c4b08.png)

### **Нет пробела**
![image](https://user-images.githubusercontent.com/5417292/55385477-ee3b4480-5535-11e9-91aa-6a0de895eb17.png)

### **Лишний пробел**
![image](https://user-images.githubusercontent.com/5417292/55385626-32c6e000-5536-11e9-8d14-3daf573dd3da.png)

### **Лишний пробел**
![image](https://user-images.githubusercontent.com/5417292/55385676-54c06280-5536-11e9-86cb-c1d0ff70b7e0.png)

![image](https://user-images.githubusercontent.com/5417292/55385775-93561d00-5536-11e9-9a66-fbdf26e0663e.png)

### И т.д. по всем нотификациям...

**Comment by Faith1ess** [comment]
исправлено
