### ISSUE TITLE
Правки 03.04.19

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#129]
**Профиль физ.лица** 
- [x] CEO role name исправить, удалить поле Occupation
- [x] Исправить + с телефоном(уточнить)
- [x] Выкатить правки по переводам
- [x] Подтвердите действия на страничке mow.... перевести (системная всплывашка, язык зависит от настроек браузера)
- [x] фиксация бабла при переходе на другую строку
- [x] Доделать список валют
- [x] Не прикрепляется документ
- [x] All My Roles-->My roles 
**Левое боковое меню**
- [x] Удалить всплывающее имя роли при наведении на роль в боковом меню
- [x] Удалить слово zoom из фильтров в Analytics вне дашбордов

**Comment by VazgenAr** [comment]
#103 
- [ ] Доделать список валют

**Comment by Laixsias** [comment]
- [ ] скрыть Tax Rate  при выборе investment

**Comment by Laixsias** [comment]
- [ ] изменить occupation в профиле компании на Activity

**Comment by Laixsias** [comment]
- [ ] профиле компании в разделе general добавить строчку CEO Role name и под ним ввести скрепку credentional documents

**Comment by VazgenAr** [comment]
На 2-ой странице мастера в строках процента и суммы поставить в проценте 0, в сумме 0.00

**Comment by VazgenAr** [comment]
- [ ] Исправить выбор исключений на второй странице мастера заказа
