### ISSUE TITLE
Автоматический выбор роли

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#139]
![Screenshot_20190410_191824](https://user-images.githubusercontent.com/43605110/55895730-6c968700-5bc5-11e9-8f92-db8593775a41.png)

При обновлении страницы автоматически не выбирается роль.
Необходимо поставить физика по умолчанию

**Comment by VazgenAr** [comment]
Добавить возможность юзеру выбирать роль по умолчанию

**Comment by gewisser** [comment]
Исправлено. Требуется проверка

**Comment by VazgenAr** [comment]
Работает
