### ISSUE TITLE
Валюты в мастере заказа работают некорректно 

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#143]
![Screenshot_20190415_121309](https://user-images.githubusercontent.com/43605110/56120938-d58c4f00-5f77-11e9-935d-1c4987297987.png)

**Comment by Faith1ess** [comment]
В store разработан getter "get_curr_obj". Метод принимает на вход ID валюты, возвращает индекс элемента в массиве с соответствующим ID

- [ ] Проверить все места, где происходит вывод названия валюты
