### ISSUE TITLE
COMMUNICATING / Contacts

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#145]
- [x]  1. Поиск по всем компаниям в системе. Искать по `Названию компании`, `почте`, `контактному телефону`, `сайту`, `ИНН/TRN`
- [x]  2. Клиент найдя нужную компанию может перейти на её хоум пейдж и связаться с её представителем 
- [x]  3. Исходя из пункта 2, необходимо определить как назначать представителя компании (кто на том проводе) для чата.

**Comment by VazgenAr** [comment]
Добавить в Employee Property
- [ ] Responsible for external communications
