### ISSUE TITLE
Восстановление работоспособности подключения служб PACE

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#148]
1. Поскольку у нас нет сейчас "продукта", необходимо разработать интерфейс создания тарифной линейки которая будет использована при подключении службы. 

**Выглядит подключение службы сейчас так:**

![Подключение службы ПАСЕ](https://user-images.githubusercontent.com/5417292/56205774-5ff5b100-6053-11e9-9e50-b0af22173369.gif)

**Те тарифы которые были выше, заносятся у привилегированной компании тут:**

![Создание тарифов в ПАСЕ](https://user-images.githubusercontent.com/5417292/56205991-ec07d880-6053-11e9-981a-b71d10bd2ef8.gif)

1. Вместо сырых JSON данных разработать интерфейс который позволяет формировать такую структуру.
2. Поскольку тарифы у нас могут быть разные для каждой локации, необходимо это учесть. Например для `mow.paceco.online` надо показывать тарифы
   
   - на русском языке
   - со своим ценообразованием
   - со своей валютой
   - и т.д.

3. Сформировавшаяся JSON структура должна храниться в базе данных для каждой из служб и когда клиент будет подключать службу, то основываясь имени домена, например, `mow.paceco.online` будет видеть свою линейку тарифов.
4. Проработать диалоговое окно выбора тарифа (см. первый скриншот). Скорей всего для разных регионов будет разный набор полей. Если такова логика будет, то её необходимо так же учесть и обыграть в разделе создания тарифов для PACE.

**Comment by gewisser** [comment]
**Пункт 1**. Пока откладываем.

**Пункт 2,3**. Какой тариф показывать, должно быть основано на основании региона регистрации текущей компании клиента. Например, если компания зарегистрирована в России, то тарифы/пакеты будут показаны для России. JSON структура должна быть доработана мной с учетом этого.

**Пункт 4.** Выполнен.

**Comment by VazgenAr** [comment]
Скрытие второго вопроса в службах BP и Офиc менеджмент
