### ISSUE TITLE
Правки 23.04

### ISSUE THREAD

**Issue by Laixsias** [gewisser/lk.paceco.online#155]
Мастер Заказа первая страница
- [x] первая строка изменить add на Enter
- [x] 3 cтрока заменить add на Enter

Мастер заказа вторая страница
- [x] внедрение поля Define date of supply в нем нужно указывать даты и время поставки процент количество . в промежутке между датой старта и датой конца. ( выглядеть должно как define of payment)
 - [x] внедрение поля Perfomance/supply locations. должно быть  всплывающее окно. в нем можно указать место или места  окончания поставки.

Глобально
- [x] Возможность полностью редактировать заказ до момента подтверждения

**Comment by Laixsias** [comment]
Сокращенная карточка заказа

- [ ] в supply нужно видеть карточку с: номер,название,описание,  от кого  - кому,даты поставки/отправки, количество общее, количество в разбитой поставке
- [ ] в payment нужно видеть карточку с: номер заказа, название, от кого - кому, даты оплат, общая сумма,  сумма по датам опат

**Comment by VazgenAr** [comment]
- [ ] Проверить на второй странице мастера балансовую гармошку на проверки
