### ISSUE TITLE
Некорректное поведение всплывающего окна выбора тарифа 

### ISSUE THREAD

**Issue by Laixsias** [gewisser/lk.paceco.online#161]
При выборе тарифа можно вообще ничего не выбирать, а просто кликнуть за пределы всплывающего окна. И получится что и служба включена и тариф не выбран. Желательно бы это исправить. Я хз чья это задача так что отмечу всех

**Comment by Laixsias** [comment]
ну и конечно вид у нее огонь просто...... особенно то что где то деньги есть где то нет....... можно как то единообразно?

**Comment by gewisser** [comment]
Первый пункт исправлен. Второе задается в структуре пакетов непосредственно по желанию руководителя  привилегированной компании пасе
