### ISSUE TITLE
Чат

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#163]
- [x] Не обновляется чат на десктопе
- [x] Чат не обновляется на мобильной версии( он не в реальном времени, приходиться обновлять чтобы получить сообщение)(IOS,Android)
- [x] Плохо работает скролл чата( цепляет страницу)
- [x] Нет никакого уведомление о приходе сообщения или автоматического открытия чата на моб. версии(IOS,Android)

![Screenshot_20190617_172537](https://user-images.githubusercontent.com/43605110/59611950-ec405500-9124-11e9-8c61-ea7c1ab204f9.png)
Временно скрыто фото
- [x] При выходы из системы с открытым чатом, чат остаётся открытым
- [x] При drag&drop xml файла, сайт погибает
- [x] При drag&drop незавершить действии вброса файла чат одвисает в состоянии как на скрине ниже
![Screenshot_20190621_110710](https://user-images.githubusercontent.com/43605110/59907860-b812b000-9414-11e9-9e87-af5b8488ecc2.png)

**Comment by VazgenAr** [comment]
- [ ] Оптимизация чата под Андроид

**Comment by VazgenAr** [comment]
-[ ] При выходы из системы с открытым чатом, чат остаётся открытым

**Comment by gewisser** [comment]
Чекаем открытость чата
