### ISSUE TITLE
Выбор языка системы

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#165]
- [x] Выбор страны при открытии https://paceco.online/#/general через селект, в зависимости от выбора должны отображаться цены и пакеты на подключения служб указанной страны
Данный выбор определяет язык страницы  https://paceco.online/#/general и https://##.paceco.online/#/login\
- [x] Добавление международных пакетов на сайт https://paceco.online/#/general
- [x] Добавление строки выбора языка системы в профиле физ. лица
- [x] Добавление выбора страны при создании новой компании (в зависимости от выбора изменяется цена и валюта)
- [x] Скрытие налогового блока в системе при выборе определенных стран, для которых не подготовлен налоговый учет.
**Гармошка на второй странице мастера** 
- [x] Для физ. лиц должна быть скрыты строки

**Comment by gewisser** [comment]
Требуется разбить задачу на мелкие. Большинство задач не отвечает названию issue
