### ISSUE TITLE
Заказ виртуальному физ-лицу

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#183]
В данный момент нельзя сделать правильный заказ виртуальному физ-лицу. 

Согласно общей идеологии работы в системе, требуется доработка создания сущности виртуального физ. лица в таблице **company** аналогично настоящему физ-лицу. Без этого заказ создается но данные не подтягиваются.

**Comment by VazgenAr** [comment]
Невозможно сделать входящий заказ виртуальному физику
