### ISSUE TITLE
Внедрение возможности поста в Instagram 

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#206]
- [x] Изменить порядок действий для получения акций
В первую очередь пользователь должен выбрать соц сеть в которой будет делать пост ему выпадет соответствующая инструкция для той или иной соц сети
- [x] При выборе Instagram добавить кнопку "Загрузить QR", которая будет загружать фото на устройство
- [x] Добавить описание о необходимости размещения своего фото в посте и добавлении туда фото QR
- [x] Кнопка "скопировать" будет копировать в буфер текст необходимый для размещения

**Comment by bttlvd** [comment]
@VazgenAr, подробные текста в студию

**Comment by gewisser** [comment]
![image](https://user-images.githubusercontent.com/5417292/74167407-430d1880-4c39-11ea-9773-3506e52bd9fd.png)
