### ISSUE TITLE
Задачи на фронт до конца февраля 

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#210]
- [x] #206 
- [ ] #207 
- [x] #208 
Верстка нотификаций на двух языках
Добавление поля для постового
- [x] добавить проверку для авторизации: если пользователь зарегался и при этом ещё не авторизовался через почту
В том месте где мы пишем неправильный логин и пароль должна появиться надпись « Необходима авторизация» 
- [x] После того как пользователь прошел регистрацию, его не перекидывает в систему
Пользователю показывается toast:
RUS
На email *  email пользователя * отправлено письмо для завершения регистрации
ENG
An email * email пользователя * has been sent to complete the registration.
- [x] Когда пользователь пытается авторизоваться без подтвержденного мэйла, выкидываем надпись где мы пишем про неверный пароль- Подтвердите email/Confirm email
- [x] Исправить верстку интерфейса постового где он вводит код с почты и сумму 
Сделать строки ввода понятнее, перевести строку ввода суммы и сделать ее по левую сторону , текст в строках темнее

**Comment by alexyavon** [comment]
Ссылка на док с тз на переделки по пэйсмаркету: https://docs.google.com/document/d/1Pd6et8-o6Xvc0qIBKrQZguI3ugYkQkwlbOk1vuPjmls/edit?usp=sharing
