### ISSUE TITLE
При получении заказа, документы не скачиваются

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#22]

**Comment by gewisser** [comment]
Документ открывается в новом окне и там есть возможность его импортировать...

**Comment by VazgenAr** [comment]
Если я хочу его скачать не открывая?

**Comment by gewisser** [comment]
Надо тогда ответить на вопрос: я хочу скачать этот док не отрывая чтобы что ...
 - посмотреть и распечатать, но распечатать можно и не скачивая.
 - отправить кому-нибудь, можно отправить поделившись ссылкой

**Comment by gewisser** [comment]
![default](https://user-images.githubusercontent.com/5417292/46470364-06c4df00-c7df-11e8-9695-6b4912277244.gif)
