### ISSUE TITLE
Ошибка с проверками при создании задания

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#236]
При создании задания поле "Описание" не подсвечивается красным

**Comment by VazgenAr** [comment]
При попытке сохранить шаблон после создания заказа/задания , не получается сохранить шаблон с выбором всех чекбоксов

**Comment by bttlvd** [comment]
Второй пункт невозможно проверить / исправить из-за невозможности залогиниться / сбросить пароль. Вынесено в отдельное issue
