### ISSUE TITLE
Наезд строк и даты

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#24]
https://r6---sn-n8v7znsl.googlevideo.com/videoplayback?id=a47b4b7de507e16f&itag=18&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-n8v7znsl&ms=nxu&mv=m&nh=IgpwcjAzLnN2bzA2KgkxMjcuMC4wLjE&pl=22&sc=yes&ei=KYyrW6O2CIWg7QSqh7Z4&susc=ph&app=fife&mime=video/mp4&dur=15.232&lmt=1537968807102935&mt=1537969015&ip=185.9.85.118&ipbits=0&expire=1537976393&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,sc,ei,susc,app,mime,dur,lmt&signature=637CF9442EA4E0A02C1F995E093D5BC08DA4E5265B08682D57A85B8678464783.1233D0DA8C25F8F5083E19CE926D0FB6E5E1A31C99AAD744ED0E1DF1625DEFE5&key=us0

**Comment by VazgenAr** [comment]
Такой же наезд происходит под отчетом

**Comment by gewisser** [comment]
@Faith1ess
