### ISSUE TITLE
Откатывать заказ при не подтверждении его выполнения

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#44]

**Comment by gewisser** [comment]
Откатывать куда?

**Comment by VazgenAr** [comment]
На шаг назад

**Comment by gewisser** [comment]
### После обсуждения с Русланом пока порешали так: ###

Если заказ не подтвержден то он закрывается и остается в таком виде. Точка. Т.е. обратного пути в системе не должно быть.

1. Если заказ не подтвердил поставщик на этапе принятия заказа на исполнения, то заказчик пересоздает заказ с новыми условиями, договорившись повторно с поставщиком. 

2. Если поставщик подтвердил заказ и идет исполнение заказа поставщиком, а на этапе исполнения у поставщика произошли изменения (количество, качество, факт наличия, и т.д.). Идет обсуждение с заказчиком новых условий поставки. Заказ поставщиком переводится в статус **"выполнено"** а заказчик не подтверждает факт выполнения заказа и создает новый исторически связанный заказ **(не реализован)**. В таком заказе, при необходимости, идет коррекция суммы заказа, количества и т.д. заранее оговоренная с поставщиком по чату. 

>  **План** нового исторически связанного заказа будет равен: **(сумма нового плана)** минус **(факт оплаты по выше историческому заказу)**

При этом возникают следующие обстоятельства:

- если получается так, что новая плановая сумма связанного заказа становится меньше плановой,  то идет сторнирование по сумме (связанный заказ с отрицательной суммой)
- если получается так, что новая плановая сумма связанного заказа становиться равной нулю, то фин доки на такой заказ не создаем.
- если получается так, что новая плановая сумма связанного заказа становится больше, то все идет как обычно

Исторически связанных заказов может быть много. Если самый последний исторический заказ был подтвержден заказчиком (заказчик согласился с фактом выполнения заказа поставщиком) то все выше исторические заказы **автоматически закрываются** и считаются исполненными.
