### ISSUE TITLE
В профиле пользователя отображается Country of residence (не должно)

### ISSUE THREAD

**Issue by Faith1ess** [gewisser/lk.paceco.online#56]

**Comment by gewisser** [comment]
Согласно документу 
[https://docs.google.com/spreadsheets/d/1Al1Wsrd3KqlFtmsyI_vaPQKfwH-hHgBCmLT1_bKZtjo/edit#gid=569370680](url)

От выбранного значения этого поля у физ лица могут быть разные налоги. Поле "Country of residence" должно быть и участвует в расчете налогов.
