### ISSUE TITLE
Раздел "Мероприятия" (Events) для ПП 

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#64]
### Мероприятия будут хранится в базе данных в формате JSON.
Для админов PACE должна быть видна кнопка **редактирования** и **удаления** мероприятия 
- По нажатию кнопки **удаления** -> Вы точно хотите удалить? -> ДА -> Удалить... ;
- По нажатию на кнопку редактирования / добавления мероприятия появится модальное окно которое должно содержать следующие поля:

#### Название мероприятия
![image](https://user-images.githubusercontent.com/5417292/50169878-8e5ebc00-02ff-11e9-8d2d-62d850d557b3.png)

#### Дата мероприятия
![image](https://user-images.githubusercontent.com/5417292/50169926-b77f4c80-02ff-11e9-9574-6776615bef34.png)

#### Место проведения мероприятия
![image](https://user-images.githubusercontent.com/5417292/50170004-f1e8e980-02ff-11e9-88bd-22b2040dfd42.png)

#### Визуальный редактор, с помощью которого форматируется описание мероприятия

![image](https://user-images.githubusercontent.com/5417292/50170095-26f53c00-0300-11e9-8539-f6e5b46a7675.png)

> По звёздам на гитхабе это второй по популярности редактор:
https://quilljs.com/

> ### Редактор нужно обернуть во вью компонент, поскольку он будет использоваться в разных местах.

---

![image](https://user-images.githubusercontent.com/5417292/50169542-d6311380-02fe-11e9-9b50-b0f436fa3dba.png)

**Comment by gewisser** [comment]
# Дополнение
Каждое событие имеет флаги:
- черновик (флаг устанавливается по умолчанию при создании нового мероприятия. Это флаг виден админам ПП и его можно снимать админам ПП. При снятии флага данное мероприятие будет видно всем)
- "в архив" (данный флаг будет устанавливаться админами ПП, когда мероприятие более не актуально. При установки флага, событие исчезнет из списка, даже у админов ПП, но его можно будет восстановить админам базы данных)

**Comment by Faith1ess** [comment]
за исключением одного момента, связанного с quill editor, все готово
