### ISSUE TITLE
Промо онлайн 

### ISSUE THREAD

**Issue by gewisser** [gewisser/lk.paceco.online#66]
1. Необходимо максимально заполнить контентом список материалов которые в ближайшее время будут использованы. 

2. Сверстать для каждого из списка контент (текст, картинки, видео). Если контент отсутсвует, то необходимо его начать составлять, сейчас заполнить фейковыми данными.

3. Настроить открытие онлайн материала для всех пользователей.

**Comment by Faith1ess** [comment]
контент одной страницы частично заполнен, открытие без авторизации включено
