### ISSUE TITLE
Некорректное отображение валюты

### ISSUE THREAD

**Issue by Faith1ess** [gewisser/lk.paceco.online#78]
Валюта в order description берётся из company properties и не пересчитывается по курсу

**Comment by gewisser** [comment]
Сейчас конечная валюта заказа в AED. Скорей всего выбор валюты в свойствах компании необходимо запретить и установить по умолчанию в AED.

**Comment by VazgenAr** [comment]
Компания работает в EUR, Заказ был отправлен на 1000 дирхам

![123123123](https://user-images.githubusercontent.com/43605110/51538600-cdce7a00-1e62-11e9-981f-7b6ead5769c5.png)
 
Заказ пришел на 1000 USD

![2019-01-22](https://user-images.githubusercontent.com/43605110/51538688-01a99f80-1e63-11e9-99fe-7028d19925a2.jpg)

**Comment by gewisser** [comment]
У нас нет сейчас обратного пересчета на ту валюту, которая указана в свойствах компании. Любой заказ конвертится в AED по курсу создания заказа. Обратной конвертации на выбранную валюту нет. 
Если есть необходимость конвертировать заказ в валюту компани, то вопрос:
По какому курсу?
Курс фиксированный? На какую дату?
Курс всегда пересчитывается во время открытия карточки заказа?

Если курс фиксированный и был когда-то сохранен, то как считать, если вдруг  валюту клиент поменяет на другую и откроет карточку заказа?

**Comment by gewisser** [comment]
Закрыто по причине не актуальности функционала
