### ISSUE TITLE
Сообщение с QR кодом

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#79]
После подтверждения посещения event, в уведомлении на почту приходит только qr код, остальные данные, такие как геолокация и скрин не приходят

**Comment by VazgenAr** [comment]
QR код нельзя сканировать повторно, имеет смысл сделать его сканируемым повторно
Допустим при прверке QR кода

**Comment by gewisser** [comment]
> QR код нельзя сканировать повторно, имеет смысл сделать его сканируемым повторно
> Допустим при прверке QR кода

Технически это сложнее сделать. Билет после сканирования становится в статус "Предъявлен" и среди ожидающих его больше нет...
