### ISSUE TITLE
Давать возможность после отправки заказа изменять время на его подтверждение

### ISSUE THREAD

**Issue by VazgenAr** [gewisser/lk.paceco.online#93]
![](https://user-images.githubusercontent.com/5417292/51925368-f1b03380-23ff-11e9-96df-1cd0e6145214.gif)
Давать возможность после отправки заказа изменять время на его подтверждение

**Comment by gewisser** [comment]
Данный параметр теперь может меняться вместе со всеми параметрами заказа
